#!/usr/bin/env bash

set -euo pipefail

# Chezmoi
sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply https://github.com/victor1234/dfdc.git

# Mise
curl https://mise.run/bash | sh

# Bash aliases
echo "alias e='exit'" >>~/.bash_aliases

# Setup git
git config --global alias.st status
git config --global alias.co commit
git config --global alias.ch checkout

exit 0
