#!/usr/bin/env bash

set -euo pipefail

# Chezmoi
sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply https://github.com/victor1234/dfdc.git

# Bash aliases
echo "alias e='exit'" >>~/.bash_aliases

exit 0
